### ISSUE TITLE
有关线上 线下模式的问题

### ISSUE THREAD

**Issue by yearing1017** [LogicJake/tianchi-news-recommendation#3]
您好，看了您的代码，您在离线的时候就将（训练集+测试集）作为总的点击日志，然后分别给验证集+测试集的用户做召回。再对验证集做正负label，作为lgbm排序模型的训练集。最后拿验证集训练的排序模型给测试集做排序。
1. 我看了别的实现，有在线上模式的时候才将（训练集+测试集）合并，您这样实现是为了节省训练时间吗？
2. 训练排序模型的时候，是只能用验证集去训练吗？不能使用测试集做正负label，然后训练排序模型吗？这样是不是就过拟合了？

**Comment by LogicJake** [comment]
1. 是的
2. 测试集没法做正负label，测试集的真实点击都没有

**Comment by yearing1017** [comment]
可是，测试集的真实点击没有不是您在query中设定的-1吗？要是不设定的话，query中只有测试集，click中为（训练+测试），然后对query中的测试集用户召回，做正负label，然后训练排序模型。这样是不是就违背了训练的准则了（拿离线验证集训练的模型去给测试集做排序），这样做是不是模型只对测试集的有效果，过拟合了？请教一下，谢谢您。
还有一个问题，可以问下您在训练lgbm排序模型的时候，AUC大约是多少呢最后

**Comment by LogicJake** [comment]
是不是我们对测试集理解不一样。原始数据训练集才有label，测试集是待预测的，没有真实label。我为了做线下验证，从训练集用户中采样了一部分用户作为验证集用户。召回的时候对所有用户进行召回，构造排序样本。这时候训练集和验证集都是有真实的排序样本标签的，但是只用了训练集数据训练排序模型，验证集数据只做早停和线下指标计算，验证集并没有参与模型训练。
