### ISSUE TITLE
样本划分及label，召回问题

### ISSUE THREAD

**Issue by chen849157649** [LogicJake/tianchi-news-recommendation#6]
谢谢您的分享，你先随机抽取5万用户，然后将这批用户的点击序列最后一个样本和测试集合并作为df_query, 后期使用df_query的用户去召回样本，构造正负label。除开序列最后一个样本外的训练集和测试集合并全部作为训练集。但是这部分数据，你并未给label，同样也没有召回。有问题吧？望解答。

![企业微信截图_20210415172040](https://user-images.githubusercontent.com/32058220/114848795-a6807080-9e11-11eb-8286-b00e0176b725.png)

**Comment by LogicJake** [comment]
这里的训练集和常规的数据场景下的训练集不太一样，click数据作为全部的历史点击记录用来训练itemcf等召回模型，然后针对val用户进行召回线下验证。

**Comment by chen849157649** [comment]
> 这里的训练集和常规的数据场景下的训练集不太一样，click数据作为全部的历史点击记录用来训练itemcf等召回模型，然后针对val用户进行召回线下验证。

@LogicJake ，第一，click数据根据您的代码逻辑并没有label，如何训练，第二，包括recall_final都是针对df_query的user_id的召回。合并召回时，你注释删除无正样本的训练集用户，但是并未删除
![企业微信截图_20210415183047](https://user-images.githubusercontent.com/32058220/114855772-e3039a80-9e18-11eb-9834-ec8342940847.png)
![企业微信截图_20210415183248](https://user-images.githubusercontent.com/32058220/114855948-11817580-9e19-11eb-88f9-1e9e98638515.png)
运行代码发现user_id数量82028，点击只有32028说明召回的样本作为训练集，很多无正样本并未删除。
第三，特征工程时，你使用了点击时间戳的一些统计计数特征，但是实质上线上预测时，并未有点击时间戳，你这种操作是不是意味着存在穿越特征啦。
第四，按照您的代码，整个训练集包括开始划分那部分click数据，和从df_query召回的数据，只有你取的5万用户才有点击行为训练，其他25万用户label就会全是0。但训练的时候并未剔除无正样本的用户。确实与常规的方式不同，常规的是训练集用户都有正样本，验证集也是，且验证集的用户必须出现于训练集之中。
我仔细看完您的代码后，主要有这些疑问，希望您能抽时间帮我解答一下，万分感谢。

**Comment by LogicJake** [comment]
itemcf学习不需要label，根据点击记录学习item之间的相关关系。后续召回和排序，训练和验证用户均出于采样的5w用户，用到的几点时间戳都是用户历史点击的，线上预测也可以拿到。

**Comment by chen849157649** [comment]
@LogicJake 谢谢，还是有点疑问，itemCF在计算相似度是你说的这个道理，用户的点击序列会出现共现情况，根据点击记录学习item之间的相关关系。但是最终排序模型的样本记那25万用户没有正样本呢，这个不影响吗？另外这个采样5万，数量设置是随机，若是极端情况，就是我们平时常规训练方式，30万用户都用上，都有正样本，可以吗？你这种处理方式与整个训练集用户都有正样本的方式有何优势或者合理性。

**Comment by chen849157649** [comment]
@LogicJake 谢谢，还是有点疑问，itemCF在计算相似度是你说的这个道理，用户的点击序列会出现共现情况，根据点击记录学习item之间的相关关系。但是最终排序模型的样本记那25万用户没有正样本呢，这个不影响吗？另外这个采样5万，数量设置是随机，若是极端情况，就是我们平时常规训练方式，30万用户都用上，都有正样本，可以吗？你这种处理方式与整个训练集用户都有正样本的方式有何优势或者合理性。

**Comment by chen849157649** [comment]
@LogicJake ，对不起，是我自己代码看的不够仔细，刚才又看了一遍，（上个问题可以忽略），你在特征工程中merge，使用how=left，意味着一直都是在那5万用户的召回集上做特征工程。那就没问题，怪我不够细心，该批评。排序模型的训练集你代码说删除无正样本的用户，似乎并未删掉呢，同时if那句不懂。再有一点，我是否可以将整个click数据集的用户都用来召回，然后都作为排序模型的训练集。

**Comment by LogicJake** [comment]
* 5万用户是有真实的点击商品的，但是在召回阶段并不一定能够召回到真实点击的商品，从而在构造后续排序的训练集的时候，就会出现这些用户召回的所有商品的label都是0，从而label_sum=0，从而没有被保留。
* 可以将整个click数据集的用户都用来召回做排序的训练集，这里的5w一方面是出于计算资源的考虑，一方面是为了切近线上测试集的用户规模。

**Comment by chen849157649** [comment]
@LogicJake ，我对召回样本不做采样，训练时[1800]	train's auc: 0.967529	valid's auc: 0.953309,  另外我对用户分组采样，比例1:5左右，[1700]	train's auc: 0.976448	valid's auc: 0.957017, 这训练auc高的有点离谱啊，你当时也是这样吗？你代码里未做采样。

**Comment by LogicJake** [comment]
auc高正常，因为正样本相较于负样本很少，存在大量负样本的情况下，auc会非常高
